// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeRI5PMsAhjHfTIvp6jbgAbBNn-QeCpk',
    appId: '1:999297354413:web:3a35ca08697223ed65d424',
    messagingSenderId: '999297354413',
    projectId: 'meadowmiles-46fc1',
    authDomain: 'meadowmiles-46fc1.firebaseapp.com',
    storageBucket: 'meadowmiles-46fc1.firebasestorage.app',
    measurementId: 'G-HJB850SJGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilFJapeVmk7pp9LJrH2Y3GfUQTOEXLes',
    appId: '1:999297354413:android:56fb1bb4842787b265d424',
    messagingSenderId: '999297354413',
    projectId: 'meadowmiles-46fc1',
    storageBucket: 'meadowmiles-46fc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBXCxKLGKR8LjoJBIaYjfmOXJrjIYWXY',
    appId: '1:999297354413:ios:16b33470cc5939f565d424',
    messagingSenderId: '999297354413',
    projectId: 'meadowmiles-46fc1',
    storageBucket: 'meadowmiles-46fc1.firebasestorage.app',
    iosClientId: '999297354413-h7nral46oo82lo0cjpf707ckpecun4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.meadowmiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDBXCxKLGKR8LjoJBIaYjfmOXJrjIYWXY',
    appId: '1:999297354413:ios:16b33470cc5939f565d424',
    messagingSenderId: '999297354413',
    projectId: 'meadowmiles-46fc1',
    storageBucket: 'meadowmiles-46fc1.firebasestorage.app',
    iosClientId: '999297354413-h7nral46oo82lo0cjpf707ckpecun4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.meadowmiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbeRI5PMsAhjHfTIvp6jbgAbBNn-QeCpk',
    appId: '1:999297354413:web:aa86ff57ee586fc965d424',
    messagingSenderId: '999297354413',
    projectId: 'meadowmiles-46fc1',
    authDomain: 'meadowmiles-46fc1.firebaseapp.com',
    storageBucket: 'meadowmiles-46fc1.firebasestorage.app',
    measurementId: 'G-8KFJ18HKDV',
  );

}